server {
    listen 3002;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    add_header Access-Control-Allow-Origin *;
    add_header Access-Control-Allow-Methods "GET, OPTIONS";
    add_header Access-Control-Allow-Headers "Content-Type, Authorization";

    location /_expo/ {
        types {
            application/javascript hbc;
        }
        add_header Cache-Control "no-cache";
    }

    location /assets/ {
        add_header Cache-Control "public, max-age=31536000, immutable";
    }

    location = /metadata.json {
        add_header Cache-Control "no-store";
    }

    location = /assetmap.json {
        add_header Cache-Control "no-cache";
    }
}
